import { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { ArrowLeft, BellRing } from "lucide-react";
import PortalLayout from "../../layouts/PortalLayout.jsx";
import { adminApi } from "../../api/adminApi.js";

export default function AdminSecurityAlertsPage() {
  const location = useLocation();
  const selectedAlertId = location.state?.selectedAlertId || "";

  const [alerts, setAlerts] = useState([]);

  useEffect(() => {
    adminApi.getSecurityAlerts().then(setAlerts);
  }, []);

  const selectedAlert = alerts.find((alert) => alert.id === selectedAlertId);
  const visibleAlerts = selectedAlert ? [selectedAlert] : alerts;

  return (
    <PortalLayout>
      <section className="subpage-header">
        <div>
          <span className="eyebrow">Administrator Portal</span>
          <h1>Security Alerts</h1>
          <p>
            Review security events generated by identity, data, endpoint, and
            authorization layers.
          </p>
        </div>

        <Link className="secondary-button" to="/admin">
          <ArrowLeft size={16} />
          Back to Dashboard
        </Link>
      </section>

      {selectedAlert && (
        <section className="panel selected-notice-panel">
          <div className="selected-course-header">
            <BellRing size={22} />
            <div>
              <span className="eyebrow">Selected Alert</span>
              <h2>{selectedAlert.title}</h2>
            </div>
          </div>

          <p>{selectedAlert.description}</p>

          <div className="selected-course-meta">
            <span>{selectedAlert.severity}</span>
            <span>{selectedAlert.source}</span>
            <span>{selectedAlert.status}</span>
            <span>{selectedAlert.time}</span>
          </div>
        </section>
      )}

      <section className="panel">
        <div className="notice-list">
          {visibleAlerts.map((alert) => (
            <article className="notice-detail-card" key={alert.id}>
              <div className="notice-detail-icon">
                <BellRing size={22} />
              </div>

              <div>
                <h3>{alert.title}</h3>
                <p>{alert.description}</p>

                <div className="notice-meta">
                  <span className={`notice-severity ${alert.severity.toLowerCase()}`}>
                    {alert.severity}
                  </span>
                  <span>{alert.source}</span>
                  <span>{alert.status}</span>
                  <span>{alert.time}</span>
                </div>

                {!selectedAlert && (
                  <Link
                    className="card-link notice-read-more"
                    to="/admin/security-alerts"
                    state={{ selectedAlertId: alert.id }}
                  >
                    View alert details
                  </Link>
                )}
              </div>
            </article>
          ))}
        </div>
      </section>

    </PortalLayout>
  );
}